// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	FindCharacterByID(ctx context.Context, id int64) (Character, error)
	ListCharacters(ctx context.Context) ([]Character, error)
}

var _ Querier = (*Queries)(nil)
