// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    owner_id,
    is_npc,
    name,
    race,
    class,
    level,
    max_hp,
    current_hp,
    armor_class,
    speed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type CreateCharacterParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	IsNpc      bool        `json:"is_npc"`
	Name       string      `json:"name"`
	Race       string      `json:"race"`
	Class      string      `json:"class"`
	Level      int32       `json:"level"`
	MaxHp      int32       `json:"max_hp"`
	CurrentHp  int32       `json:"current_hp"`
	ArmorClass int32       `json:"armor_class"`
	Speed      int32       `json:"speed"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.OwnerID,
		arg.IsNpc,
		arg.Name,
		arg.Race,
		arg.Class,
		arg.Level,
		arg.MaxHp,
		arg.CurrentHp,
		arg.ArmorClass,
		arg.Speed,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
ORDER BY name
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.Inspiration,
			&i.TrainingArmor,
			&i.TrainingWeapons,
			&i.TrainingTools,
			&i.TrainingLanguages,
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			&i.Conditions,
			&i.Resistances,
			&i.Vulnerabilities,
			&i.Immunities,
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNPCs = `-- name: ListNPCs :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE is_npc = TRUE
ORDER BY name
`

func (q *Queries) ListNPCs(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, listNPCs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.Inspiration,
			&i.TrainingArmor,
			&i.TrainingWeapons,
			&i.TrainingTools,
			&i.TrainingLanguages,
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			&i.Conditions,
			&i.Resistances,
			&i.Vulnerabilities,
			&i.Immunities,
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerCharacters = `-- name: ListPlayerCharacters :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE is_npc = FALSE
ORDER BY name
`

func (q *Queries) ListPlayerCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, listPlayerCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.Inspiration,
			&i.TrainingArmor,
			&i.TrainingWeapons,
			&i.TrainingTools,
			&i.TrainingLanguages,
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			&i.Conditions,
			&i.Resistances,
			&i.Vulnerabilities,
			&i.Immunities,
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const longRest = `-- name: LongRest :one
UPDATE characters
SET
    current_hp              = max_hp,
    hit_dice_remaining      = GREATEST(hit_dice_remaining + (level / 2), level),
    death_save_successes    = 0,
    death_save_failures     = 0,
    conditions              = '{}',
    updated_at              = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

func (q *Queries) LongRest(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, longRest, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetDeathSaves = `-- name: ResetDeathSaves :one
UPDATE characters
SET
    death_save_successes    = 0,
    death_save_failures     = 0,
    updated_at              = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

func (q *Queries) ResetDeathSaves(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, resetDeathSaves, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const shortRest = `-- name: ShortRest :one
UPDATE characters
SET
    hit_dice_remaining      = GREATEST(hit_dice_remaining - $2, 0),
    current_hp              = LEAST(current_hp + $3, max_hp),
    updated_at              = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type ShortRestParams struct {
	ID               uuid.UUID `json:"id"`
	HitDiceRemaining int32     `json:"hit_dice_remaining"`
	CurrentHp        int32     `json:"current_hp"`
}

func (q *Queries) ShortRest(ctx context.Context, arg ShortRestParams) (Character, error) {
	row := q.db.QueryRow(ctx, shortRest, arg.ID, arg.HitDiceRemaining, arg.CurrentHp)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters
SET
    name                   = COALESCE($1, name),
    race                   = COALESCE($2, race),
    class                  = COALESCE($3, class),
    level                  = COALESCE($4, level),
    background             = COALESCE($5, background),
    alignment              = COALESCE($6, alignment),
    xp                     = COALESCE($7, xp),
    strength               = COALESCE($8, strength),
    dexterity              = COALESCE($9, dexterity),
    constitution           = COALESCE($10, constitution),
    intelligence           = COALESCE($11, intelligence),
    wisdom                 = COALESCE($12, wisdom),
    charisma               = COALESCE($13, charisma),
    save_prof_strength     = COALESCE($14, save_prof_strength),
    save_prof_dexterity    = COALESCE($15, save_prof_dexterity),
    save_prof_constitution = COALESCE($16, save_prof_constitution),
    save_prof_intelligence = COALESCE($17, save_prof_intelligence),
    save_prof_wisdom       = COALESCE($18, save_prof_wisdom),
    save_prof_charisma     = COALESCE($19, save_prof_charisma),
    skill_acrobatics       = COALESCE($20, skill_acrobatics),
    skill_animal_handling  = COALESCE($21, skill_animal_handling),
    skill_arcana           = COALESCE($22, skill_arcana),
    skill_athletics        = COALESCE($23, skill_athletics),
    skill_deception        = COALESCE($24, skill_deception),
    skill_history          = COALESCE($25, skill_history),
    skill_insight          = COALESCE($26, skill_insight),
    skill_intimidation     = COALESCE($27, skill_intimidation),
    skill_investigation    = COALESCE($28, skill_investigation),
    skill_medicine         = COALESCE($29, skill_medicine),
    skill_nature           = COALESCE($30, skill_nature),
    skill_perception       = COALESCE($31, skill_perception),
    skill_performance      = COALESCE($32, skill_performance),
    skill_persuasion       = COALESCE($33, skill_persuasion),
    skill_religion         = COALESCE($34, skill_religion),
    skill_sleight_of_hand  = COALESCE($35, skill_sleight_of_hand),
    skill_stealth          = COALESCE($36, skill_stealth),
    skill_survival         = COALESCE($37, skill_survival),
    armor_class            = COALESCE($38, armor_class),
    speed                  = COALESCE($39, speed),
    max_hp                 = COALESCE($40, max_hp),
    hit_dice_type          = COALESCE($41, hit_dice_type),
    hit_dice_remaining     = COALESCE($42, hit_dice_remaining),
    inspiration            = COALESCE($43, inspiration),
    attunement_slots       = COALESCE($44, attunement_slots),
    training_armor         = COALESCE($45, training_armor),
    training_weapons       = COALESCE($46, training_weapons),
    training_tools         = COALESCE($47, training_tools),
    training_languages     = COALESCE($48, training_languages),
    copper                 = COALESCE($49, copper),
    silver                 = COALESCE($50, silver),
    electrum               = COALESCE($51, electrum),
    gold                   = COALESCE($52, gold),
    platinum               = COALESCE($53, platinum),
    conditions             = COALESCE($54, conditions),
    resistances            = COALESCE($55, resistances),
    vulnerabilities        = COALESCE($56, vulnerabilities),
    immunities             = COALESCE($57, immunities),
    personality_traits     = COALESCE($58, personality_traits),
    ideals                 = COALESCE($59, ideals),
    bonds                  = COALESCE($60, bonds),
    flaws                  = COALESCE($61, flaws),
    notes                  = COALESCE($62, notes),
    updated_at             = NOW()
WHERE id = $63
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterParams struct {
	Name                 pgtype.Text `json:"name"`
	Race                 pgtype.Text `json:"race"`
	Class                pgtype.Text `json:"class"`
	Level                pgtype.Int4 `json:"level"`
	Background           pgtype.Text `json:"background"`
	Alignment            pgtype.Text `json:"alignment"`
	Xp                   pgtype.Int4 `json:"xp"`
	Strength             pgtype.Int4 `json:"strength"`
	Dexterity            pgtype.Int4 `json:"dexterity"`
	Constitution         pgtype.Int4 `json:"constitution"`
	Intelligence         pgtype.Int4 `json:"intelligence"`
	Wisdom               pgtype.Int4 `json:"wisdom"`
	Charisma             pgtype.Int4 `json:"charisma"`
	SaveProfStrength     pgtype.Bool `json:"save_prof_strength"`
	SaveProfDexterity    pgtype.Bool `json:"save_prof_dexterity"`
	SaveProfConstitution pgtype.Bool `json:"save_prof_constitution"`
	SaveProfIntelligence pgtype.Bool `json:"save_prof_intelligence"`
	SaveProfWisdom       pgtype.Bool `json:"save_prof_wisdom"`
	SaveProfCharisma     pgtype.Bool `json:"save_prof_charisma"`
	SkillAcrobatics      pgtype.Int4 `json:"skill_acrobatics"`
	SkillAnimalHandling  pgtype.Int4 `json:"skill_animal_handling"`
	SkillArcana          pgtype.Int4 `json:"skill_arcana"`
	SkillAthletics       pgtype.Int4 `json:"skill_athletics"`
	SkillDeception       pgtype.Int4 `json:"skill_deception"`
	SkillHistory         pgtype.Int4 `json:"skill_history"`
	SkillInsight         pgtype.Int4 `json:"skill_insight"`
	SkillIntimidation    pgtype.Int4 `json:"skill_intimidation"`
	SkillInvestigation   pgtype.Int4 `json:"skill_investigation"`
	SkillMedicine        pgtype.Int4 `json:"skill_medicine"`
	SkillNature          pgtype.Int4 `json:"skill_nature"`
	SkillPerception      pgtype.Int4 `json:"skill_perception"`
	SkillPerformance     pgtype.Int4 `json:"skill_performance"`
	SkillPersuasion      pgtype.Int4 `json:"skill_persuasion"`
	SkillReligion        pgtype.Int4 `json:"skill_religion"`
	SkillSleightOfHand   pgtype.Int4 `json:"skill_sleight_of_hand"`
	SkillStealth         pgtype.Int4 `json:"skill_stealth"`
	SkillSurvival        pgtype.Int4 `json:"skill_survival"`
	ArmorClass           pgtype.Int4 `json:"armor_class"`
	Speed                pgtype.Int4 `json:"speed"`
	MaxHp                pgtype.Int4 `json:"max_hp"`
	HitDiceType          pgtype.Int4 `json:"hit_dice_type"`
	HitDiceRemaining     pgtype.Int4 `json:"hit_dice_remaining"`
	Inspiration          pgtype.Bool `json:"inspiration"`
	AttunementSlots      pgtype.Int4 `json:"attunement_slots"`
	TrainingArmor        []string    `json:"training_armor"`
	TrainingWeapons      []string    `json:"training_weapons"`
	TrainingTools        []string    `json:"training_tools"`
	TrainingLanguages    []string    `json:"training_languages"`
	Copper               pgtype.Int4 `json:"copper"`
	Silver               pgtype.Int4 `json:"silver"`
	Electrum             pgtype.Int4 `json:"electrum"`
	Gold                 pgtype.Int4 `json:"gold"`
	Platinum             pgtype.Int4 `json:"platinum"`
	Conditions           []string    `json:"conditions"`
	Resistances          []string    `json:"resistances"`
	Vulnerabilities      []string    `json:"vulnerabilities"`
	Immunities           []string    `json:"immunities"`
	PersonalityTraits    pgtype.Text `json:"personality_traits"`
	Ideals               pgtype.Text `json:"ideals"`
	Bonds                pgtype.Text `json:"bonds"`
	Flaws                pgtype.Text `json:"flaws"`
	Notes                pgtype.Text `json:"notes"`
	ID                   uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacter,
		arg.Name,
		arg.Race,
		arg.Class,
		arg.Level,
		arg.Background,
		arg.Alignment,
		arg.Xp,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
		arg.SaveProfStrength,
		arg.SaveProfDexterity,
		arg.SaveProfConstitution,
		arg.SaveProfIntelligence,
		arg.SaveProfWisdom,
		arg.SaveProfCharisma,
		arg.SkillAcrobatics,
		arg.SkillAnimalHandling,
		arg.SkillArcana,
		arg.SkillAthletics,
		arg.SkillDeception,
		arg.SkillHistory,
		arg.SkillInsight,
		arg.SkillIntimidation,
		arg.SkillInvestigation,
		arg.SkillMedicine,
		arg.SkillNature,
		arg.SkillPerception,
		arg.SkillPerformance,
		arg.SkillPersuasion,
		arg.SkillReligion,
		arg.SkillSleightOfHand,
		arg.SkillStealth,
		arg.SkillSurvival,
		arg.ArmorClass,
		arg.Speed,
		arg.MaxHp,
		arg.HitDiceType,
		arg.HitDiceRemaining,
		arg.Inspiration,
		arg.AttunementSlots,
		arg.TrainingArmor,
		arg.TrainingWeapons,
		arg.TrainingTools,
		arg.TrainingLanguages,
		arg.Copper,
		arg.Silver,
		arg.Electrum,
		arg.Gold,
		arg.Platinum,
		arg.Conditions,
		arg.Resistances,
		arg.Vulnerabilities,
		arg.Immunities,
		arg.PersonalityTraits,
		arg.Ideals,
		arg.Bonds,
		arg.Flaws,
		arg.Notes,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterHP = `-- name: UpdateCharacterHP :one
UPDATE characters
SET
    current_hp = $2,
    temp_hp    = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterHPParams struct {
	ID        uuid.UUID `json:"id"`
	CurrentHp int32     `json:"current_hp"`
	TempHp    int32     `json:"temp_hp"`
}

func (q *Queries) UpdateCharacterHP(ctx context.Context, arg UpdateCharacterHPParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterHP, arg.ID, arg.CurrentHp, arg.TempHp)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConditions = `-- name: UpdateConditions :one
UPDATE characters
SET
    conditions = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateConditionsParams struct {
	ID         uuid.UUID `json:"id"`
	Conditions []string  `json:"conditions"`
}

func (q *Queries) UpdateConditions(ctx context.Context, arg UpdateConditionsParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateConditions, arg.ID, arg.Conditions)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeathSaves = `-- name: UpdateDeathSaves :one
UPDATE characters
SET
    death_save_successes    = $2,
    death_save_failures     = $3,
    updated_at              = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateDeathSavesParams struct {
	ID                 uuid.UUID `json:"id"`
	DeathSaveSuccesses int32     `json:"death_save_successes"`
	DeathSaveFailures  int32     `json:"death_save_failures"`
}

func (q *Queries) UpdateDeathSaves(ctx context.Context, arg UpdateDeathSavesParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateDeathSaves, arg.ID, arg.DeathSaveSuccesses, arg.DeathSaveFailures)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
