// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    owner_id,
    is_npc,
    name,
    race,
    class,
    level,
    max_hp,
    current_hp,
    armor_class,
    speed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type CreateCharacterParams struct {
	OwnerID    uuid.NullUUID `json:"owner_id"`
	IsNpc      bool          `json:"is_npc"`
	Name       string        `json:"name"`
	Race       string        `json:"race"`
	Class      string        `json:"class"`
	Level      int32         `json:"level"`
	MaxHp      int32         `json:"max_hp"`
	CurrentHp  int32         `json:"current_hp"`
	ArmorClass int32         `json:"armor_class"`
	Speed      int32         `json:"speed"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.OwnerID,
		arg.IsNpc,
		arg.Name,
		arg.Race,
		arg.Class,
		arg.Level,
		arg.MaxHp,
		arg.CurrentHp,
		arg.ArmorClass,
		arg.Speed,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		pq.Array(&i.TrainingArmor),
		pq.Array(&i.TrainingWeapons),
		pq.Array(&i.TrainingTools),
		pq.Array(&i.TrainingLanguages),
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		pq.Array(&i.Conditions),
		pq.Array(&i.Resistances),
		pq.Array(&i.Vulnerabilities),
		pq.Array(&i.Immunities),
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		pq.Array(&i.TrainingArmor),
		pq.Array(&i.TrainingWeapons),
		pq.Array(&i.TrainingTools),
		pq.Array(&i.TrainingLanguages),
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		pq.Array(&i.Conditions),
		pq.Array(&i.Resistances),
		pq.Array(&i.Vulnerabilities),
		pq.Array(&i.Immunities),
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
ORDER BY name
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.Inspiration,
			pq.Array(&i.TrainingArmor),
			pq.Array(&i.TrainingWeapons),
			pq.Array(&i.TrainingTools),
			pq.Array(&i.TrainingLanguages),
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			pq.Array(&i.Conditions),
			pq.Array(&i.Resistances),
			pq.Array(&i.Vulnerabilities),
			pq.Array(&i.Immunities),
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNPCs = `-- name: ListNPCs :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE is_npc = TRUE
ORDER BY name
`

func (q *Queries) ListNPCs(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listNPCs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.Inspiration,
			pq.Array(&i.TrainingArmor),
			pq.Array(&i.TrainingWeapons),
			pq.Array(&i.TrainingTools),
			pq.Array(&i.TrainingLanguages),
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			pq.Array(&i.Conditions),
			pq.Array(&i.Resistances),
			pq.Array(&i.Vulnerabilities),
			pq.Array(&i.Immunities),
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerCharacters = `-- name: ListPlayerCharacters :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE is_npc = FALSE
ORDER BY name
`

func (q *Queries) ListPlayerCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.Inspiration,
			pq.Array(&i.TrainingArmor),
			pq.Array(&i.TrainingWeapons),
			pq.Array(&i.TrainingTools),
			pq.Array(&i.TrainingLanguages),
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			pq.Array(&i.Conditions),
			pq.Array(&i.Resistances),
			pq.Array(&i.Vulnerabilities),
			pq.Array(&i.Immunities),
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterHP = `-- name: UpdateCharacterHP :one
UPDATE characters
SET
    current_hp = $2,
    temp_hp    = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterHPParams struct {
	ID        uuid.UUID `json:"id"`
	CurrentHp int32     `json:"current_hp"`
	TempHp    int32     `json:"temp_hp"`
}

func (q *Queries) UpdateCharacterHP(ctx context.Context, arg UpdateCharacterHPParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacterHP, arg.ID, arg.CurrentHp, arg.TempHp)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.Inspiration,
		pq.Array(&i.TrainingArmor),
		pq.Array(&i.TrainingWeapons),
		pq.Array(&i.TrainingTools),
		pq.Array(&i.TrainingLanguages),
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		pq.Array(&i.Conditions),
		pq.Array(&i.Resistances),
		pq.Array(&i.Vulnerabilities),
		pq.Array(&i.Immunities),
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
