// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: combat.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO combat_participants (
    encounter_id,
    character_id,
    name,
    initiative,
    current_hp,
    max_hp,
    temp_hp,
    armor_class,
    speed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes
`

type AddParticipantParams struct {
	EncounterID uuid.UUID `json:"encounter_id"`
	CharacterID uuid.UUID `json:"character_id"`
	Name        string    `json:"name"`
	Initiative  int32     `json:"initiative"`
	CurrentHp   int32     `json:"current_hp"`
	MaxHp       int32     `json:"max_hp"`
	TempHp      int32     `json:"temp_hp"`
	ArmorClass  int32     `json:"armor_class"`
	Speed       int32     `json:"speed"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (CombatParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipant,
		arg.EncounterID,
		arg.CharacterID,
		arg.Name,
		arg.Initiative,
		arg.CurrentHp,
		arg.MaxHp,
		arg.TempHp,
		arg.ArmorClass,
		arg.Speed,
	)
	var i CombatParticipant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.Name,
		&i.Initiative,
		&i.CurrentHp,
		&i.MaxHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.Conditions,
		&i.Concentration,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const createEncounter = `-- name: CreateEncounter :one
INSERT INTO combat_encounters (name)
VALUES ($1)
RETURNING id, name, is_active, round, created_at
`

func (q *Queries) CreateEncounter(ctx context.Context, name string) (CombatEncounter, error) {
	row := q.db.QueryRow(ctx, createEncounter, name)
	var i CombatEncounter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Round,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateParticipant = `-- name: DeactivateParticipant :one
UPDATE combat_participants
SET is_active = FALSE
WHERE id = $1
RETURNING id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes
`

func (q *Queries) DeactivateParticipant(ctx context.Context, id uuid.UUID) (CombatParticipant, error) {
	row := q.db.QueryRow(ctx, deactivateParticipant, id)
	var i CombatParticipant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.Name,
		&i.Initiative,
		&i.CurrentHp,
		&i.MaxHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.Conditions,
		&i.Concentration,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const deleteEncounter = `-- name: DeleteEncounter :exec
DELETE FROM combat_encounters
WHERE id = $1
`

func (q *Queries) DeleteEncounter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEncounter, id)
	return err
}

const endEncounter = `-- name: EndEncounter :one
UPDATE combat_encounters
SET is_active = FALSE
WHERE id = $1
RETURNING id, name, is_active, round, created_at
`

func (q *Queries) EndEncounter(ctx context.Context, id uuid.UUID) (CombatEncounter, error) {
	row := q.db.QueryRow(ctx, endEncounter, id)
	var i CombatEncounter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Round,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveEncounter = `-- name: GetActiveEncounter :one
SELECT id, name, is_active, round, created_at FROM combat_encounters
WHERE is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveEncounter(ctx context.Context) (CombatEncounter, error) {
	row := q.db.QueryRow(ctx, getActiveEncounter)
	var i CombatEncounter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Round,
		&i.CreatedAt,
	)
	return i, err
}

const getEncounter = `-- name: GetEncounter :one
SELECT id, name, is_active, round, created_at FROM combat_encounters
WHERE id = $1
`

func (q *Queries) GetEncounter(ctx context.Context, id uuid.UUID) (CombatEncounter, error) {
	row := q.db.QueryRow(ctx, getEncounter, id)
	var i CombatEncounter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Round,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes FROM combat_participants
WHERE id = $1
`

func (q *Queries) GetParticipant(ctx context.Context, id uuid.UUID) (CombatParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i CombatParticipant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.Name,
		&i.Initiative,
		&i.CurrentHp,
		&i.MaxHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.Conditions,
		&i.Concentration,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const listActiveParticipants = `-- name: ListActiveParticipants :many
SELECT id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes FROM combat_participants
WHERE encounter_id = $1
AND is_active = TRUE
ORDER BY initiative DESC, name
`

func (q *Queries) ListActiveParticipants(ctx context.Context, encounterID uuid.UUID) ([]CombatParticipant, error) {
	rows, err := q.db.Query(ctx, listActiveParticipants, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CombatParticipant{}
	for rows.Next() {
		var i CombatParticipant
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CharacterID,
			&i.Name,
			&i.Initiative,
			&i.CurrentHp,
			&i.MaxHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.Conditions,
			&i.Concentration,
			&i.IsActive,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounters = `-- name: ListEncounters :many
SELECT id, name, is_active, round, created_at FROM combat_encounters
ORDER BY created_at DESC
`

func (q *Queries) ListEncounters(ctx context.Context) ([]CombatEncounter, error) {
	rows, err := q.db.Query(ctx, listEncounters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CombatEncounter{}
	for rows.Next() {
		var i CombatEncounter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.Round,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes FROM combat_participants
WHERE encounter_id = $1
ORDER BY initiative DESC, name
`

func (q *Queries) ListParticipants(ctx context.Context, encounterID uuid.UUID) ([]CombatParticipant, error) {
	rows, err := q.db.Query(ctx, listParticipants, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CombatParticipant{}
	for rows.Next() {
		var i CombatParticipant
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CharacterID,
			&i.Name,
			&i.Initiative,
			&i.CurrentHp,
			&i.MaxHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.Conditions,
			&i.Concentration,
			&i.IsActive,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRound = `-- name: NextRound :one
UPDATE combat_encounters
SET round = round + 1
WHERE id = $1
RETURNING id, name, is_active, round, created_at
`

func (q *Queries) NextRound(ctx context.Context, id uuid.UUID) (CombatEncounter, error) {
	row := q.db.QueryRow(ctx, nextRound, id)
	var i CombatEncounter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Round,
		&i.CreatedAt,
	)
	return i, err
}

const removeParticipant = `-- name: RemoveParticipant :exec
DELETE FROM combat_participants
WHERE id = $1
`

func (q *Queries) RemoveParticipant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeParticipant, id)
	return err
}

const startEncounter = `-- name: StartEncounter :one
UPDATE combat_encounters
SET is_active = TRUE,
    round     = 1
WHERE id = $1
RETURNING id, name, is_active, round, created_at
`

func (q *Queries) StartEncounter(ctx context.Context, id uuid.UUID) (CombatEncounter, error) {
	row := q.db.QueryRow(ctx, startEncounter, id)
	var i CombatEncounter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.Round,
		&i.CreatedAt,
	)
	return i, err
}

const toggleParticipantConcentration = `-- name: ToggleParticipantConcentration :one
UPDATE combat_participants
SET concentration = NOT concentration
WHERE id = $1
RETURNING id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes
`

func (q *Queries) ToggleParticipantConcentration(ctx context.Context, id uuid.UUID) (CombatParticipant, error) {
	row := q.db.QueryRow(ctx, toggleParticipantConcentration, id)
	var i CombatParticipant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.Name,
		&i.Initiative,
		&i.CurrentHp,
		&i.MaxHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.Conditions,
		&i.Concentration,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const updateParticipantConditions = `-- name: UpdateParticipantConditions :one
UPDATE combat_participants
SET conditions = $2
WHERE id = $1
RETURNING id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes
`

type UpdateParticipantConditionsParams struct {
	ID         uuid.UUID `json:"id"`
	Conditions []string  `json:"conditions"`
}

func (q *Queries) UpdateParticipantConditions(ctx context.Context, arg UpdateParticipantConditionsParams) (CombatParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantConditions, arg.ID, arg.Conditions)
	var i CombatParticipant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.Name,
		&i.Initiative,
		&i.CurrentHp,
		&i.MaxHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.Conditions,
		&i.Concentration,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const updateParticipantHP = `-- name: UpdateParticipantHP :one
UPDATE combat_participants
SET current_hp = $2
WHERE id = $1
RETURNING id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes
`

type UpdateParticipantHPParams struct {
	ID        uuid.UUID `json:"id"`
	CurrentHp int32     `json:"current_hp"`
}

func (q *Queries) UpdateParticipantHP(ctx context.Context, arg UpdateParticipantHPParams) (CombatParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantHP, arg.ID, arg.CurrentHp)
	var i CombatParticipant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.Name,
		&i.Initiative,
		&i.CurrentHp,
		&i.MaxHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.Conditions,
		&i.Concentration,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const updateParticipantInitiative = `-- name: UpdateParticipantInitiative :one
UPDATE combat_participants
SET initiative = $2
WHERE id = $1
RETURNING id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes
`

type UpdateParticipantInitiativeParams struct {
	ID         uuid.UUID `json:"id"`
	Initiative int32     `json:"initiative"`
}

func (q *Queries) UpdateParticipantInitiative(ctx context.Context, arg UpdateParticipantInitiativeParams) (CombatParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantInitiative, arg.ID, arg.Initiative)
	var i CombatParticipant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.Name,
		&i.Initiative,
		&i.CurrentHp,
		&i.MaxHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.Conditions,
		&i.Concentration,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const updateParticipantTempHP = `-- name: UpdateParticipantTempHP :one
UPDATE combat_participants
SET temp_hp = $2
WHERE id = $1
RETURNING id, encounter_id, character_id, name, initiative, current_hp, max_hp, temp_hp, armor_class, speed, conditions, concentration, is_active, notes
`

type UpdateParticipantTempHPParams struct {
	ID     uuid.UUID `json:"id"`
	TempHp int32     `json:"temp_hp"`
}

func (q *Queries) UpdateParticipantTempHP(ctx context.Context, arg UpdateParticipantTempHPParams) (CombatParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantTempHP, arg.ID, arg.TempHp)
	var i CombatParticipant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.Name,
		&i.Initiative,
		&i.CurrentHp,
		&i.MaxHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.Conditions,
		&i.Concentration,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}
