// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFeature = `-- name: CreateFeature :one
INSERT INTO features (
    character_id,
    name,
    source,
    description,
    action_type
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, character_id, name, source, description, created_at, action_type
`

type CreateFeatureParams struct {
	CharacterID uuid.UUID `json:"character_id"`
	Name        string    `json:"name"`
	Source      string    `json:"source"`
	Description string    `json:"description"`
	ActionType  string    `json:"action_type"`
}

func (q *Queries) CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error) {
	row := q.db.QueryRow(ctx, createFeature,
		arg.CharacterID,
		arg.Name,
		arg.Source,
		arg.Description,
		arg.ActionType,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Source,
		&i.Description,
		&i.CreatedAt,
		&i.ActionType,
	)
	return i, err
}

const deleteFeature = `-- name: DeleteFeature :exec
DELETE FROM features
WHERE id = $1
`

func (q *Queries) DeleteFeature(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFeature, id)
	return err
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, character_id, name, source, description, created_at, action_type FROM features
WHERE character_id = $1
ORDER BY action_type, name
`

func (q *Queries) ListFeatures(ctx context.Context, characterID uuid.UUID) ([]Feature, error) {
	rows, err := q.db.Query(ctx, listFeatures, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Source,
			&i.Description,
			&i.CreatedAt,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturesByActionType = `-- name: ListFeaturesByActionType :many
SELECT id, character_id, name, source, description, created_at, action_type FROM features
WHERE character_id = $1
AND action_type = $2
ORDER BY name
`

type ListFeaturesByActionTypeParams struct {
	CharacterID uuid.UUID `json:"character_id"`
	ActionType  string    `json:"action_type"`
}

func (q *Queries) ListFeaturesByActionType(ctx context.Context, arg ListFeaturesByActionTypeParams) ([]Feature, error) {
	rows, err := q.db.Query(ctx, listFeaturesByActionType, arg.CharacterID, arg.ActionType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Source,
			&i.Description,
			&i.CreatedAt,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeature = `-- name: UpdateFeature :one
UPDATE features
SET
    name        = COALESCE($1, name),
    source      = COALESCE($2, source),
    description = COALESCE($3, description),
    action_type = COALESCE($4, action_type)
WHERE id = $5
RETURNING id, character_id, name, source, description, created_at, action_type
`

type UpdateFeatureParams struct {
	Name        *string   `json:"name"`
	Source      *string   `json:"source"`
	Description *string   `json:"description"`
	ActionType  *string   `json:"action_type"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateFeature(ctx context.Context, arg UpdateFeatureParams) (Feature, error) {
	row := q.db.QueryRow(ctx, updateFeature,
		arg.Name,
		arg.Source,
		arg.Description,
		arg.ActionType,
		arg.ID,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Source,
		&i.Description,
		&i.CreatedAt,
		&i.ActionType,
	)
	return i, err
}
