// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countAttunedItems = `-- name: CountAttunedItems :one
SELECT COUNT(*) FROM inventory_items
WHERE character_id = $1
AND is_attuned = TRUE
`

func (q *Queries) CountAttunedItems(ctx context.Context, characterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttunedItems, characterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (
    character_id,
    name,
    quantity,
    weight,
    value,
    description,
    is_equipped,
    requires_attunement,
    is_attuned
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, character_id, name, quantity, weight, description, is_equipped, requires_attunement, is_attuned, created_at, value
`

type CreateInventoryItemParams struct {
	CharacterID        uuid.UUID `json:"character_id"`
	Name               string    `json:"name"`
	Quantity           int32     `json:"quantity"`
	Weight             int32     `json:"weight"`
	Value              int32     `json:"value"`
	Description        string    `json:"description"`
	IsEquipped         bool      `json:"is_equipped"`
	RequiresAttunement bool      `json:"requires_attunement"`
	IsAttuned          bool      `json:"is_attuned"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.CharacterID,
		arg.Name,
		arg.Quantity,
		arg.Weight,
		arg.Value,
		arg.Description,
		arg.IsEquipped,
		arg.RequiresAttunement,
		arg.IsAttuned,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Quantity,
		&i.Weight,
		&i.Description,
		&i.IsEquipped,
		&i.RequiresAttunement,
		&i.IsAttuned,
		&i.CreatedAt,
		&i.Value,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory_items
WHERE id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, id)
	return err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, character_id, name, quantity, weight, description, is_equipped, requires_attunement, is_attuned, created_at, value FROM inventory_items
WHERE id = $1
`

func (q *Queries) GetInventoryItem(ctx context.Context, id uuid.UUID) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItem, id)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Quantity,
		&i.Weight,
		&i.Description,
		&i.IsEquipped,
		&i.RequiresAttunement,
		&i.IsAttuned,
		&i.CreatedAt,
		&i.Value,
	)
	return i, err
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT id, character_id, name, quantity, weight, description, is_equipped, requires_attunement, is_attuned, created_at, value FROM inventory_items
WHERE character_id = $1
ORDER BY name
`

func (q *Queries) ListInventoryItems(ctx context.Context, characterID uuid.UUID) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listInventoryItems, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryItem{}
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Quantity,
			&i.Weight,
			&i.Description,
			&i.IsEquipped,
			&i.RequiresAttunement,
			&i.IsAttuned,
			&i.CreatedAt,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory_items
SET
    name                = COALESCE($1, name),
    quantity            = COALESCE($2, quantity),
    weight              = COALESCE($3, weight),
    value               = COALESCE($4, value),
    description         = COALESCE($5, description),
    is_equipped         = COALESCE($6, is_equipped),
    requires_attunement = COALESCE($7, requires_attunement),
    is_attuned          = COALESCE($8, is_attuned)
WHERE id = $9
RETURNING id, character_id, name, quantity, weight, description, is_equipped, requires_attunement, is_attuned, created_at, value
`

type UpdateInventoryItemParams struct {
	Name               *string   `json:"name"`
	Quantity           *int32    `json:"quantity"`
	Weight             *int32    `json:"weight"`
	Value              *int32    `json:"value"`
	Description        *string   `json:"description"`
	IsEquipped         *bool     `json:"is_equipped"`
	RequiresAttunement *bool     `json:"requires_attunement"`
	IsAttuned          *bool     `json:"is_attuned"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.Name,
		arg.Quantity,
		arg.Weight,
		arg.Value,
		arg.Description,
		arg.IsEquipped,
		arg.RequiresAttunement,
		arg.IsAttuned,
		arg.ID,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Quantity,
		&i.Weight,
		&i.Description,
		&i.IsEquipped,
		&i.RequiresAttunement,
		&i.IsAttuned,
		&i.CreatedAt,
		&i.Value,
	)
	return i, err
}
