// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	DeleteCharacter(ctx context.Context, id uuid.UUID) error
	GetCharacter(ctx context.Context, id uuid.UUID) (Character, error)
	ListCharacters(ctx context.Context) ([]Character, error)
	ListNPCs(ctx context.Context) ([]Character, error)
	ListPlayerCharacters(ctx context.Context) ([]Character, error)
	LongRest(ctx context.Context, id uuid.UUID) (Character, error)
	ResetDeathSaves(ctx context.Context, id uuid.UUID) (Character, error)
	ShortRest(ctx context.Context, arg ShortRestParams) (Character, error)
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error)
	UpdateCharacterHP(ctx context.Context, arg UpdateCharacterHPParams) (Character, error)
	UpdateConditions(ctx context.Context, arg UpdateConditionsParams) (Character, error)
	UpdateDeathSaves(ctx context.Context, arg UpdateDeathSavesParams) (Character, error)
}

var _ Querier = (*Queries)(nil)
