// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spells.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSpell = `-- name: CreateSpell :one
INSERT INTO spells (
    character_id,
    name,
    level,
    school,
    casting_time,
    range,
    components,
    duration,
    description,
    is_prepared
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, character_id, name, level, school, casting_time, range, components, duration, description, is_prepared, created_at
`

type CreateSpellParams struct {
	CharacterID uuid.UUID `json:"character_id"`
	Name        string    `json:"name"`
	Level       int32     `json:"level"`
	School      string    `json:"school"`
	CastingTime string    `json:"casting_time"`
	Range       string    `json:"range"`
	Components  string    `json:"components"`
	Duration    string    `json:"duration"`
	Description string    `json:"description"`
	IsPrepared  bool      `json:"is_prepared"`
}

func (q *Queries) CreateSpell(ctx context.Context, arg CreateSpellParams) (Spell, error) {
	row := q.db.QueryRow(ctx, createSpell,
		arg.CharacterID,
		arg.Name,
		arg.Level,
		arg.School,
		arg.CastingTime,
		arg.Range,
		arg.Components,
		arg.Duration,
		arg.Description,
		arg.IsPrepared,
	)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Level,
		&i.School,
		&i.CastingTime,
		&i.Range,
		&i.Components,
		&i.Duration,
		&i.Description,
		&i.IsPrepared,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSpell = `-- name: DeleteSpell :exec
DELETE FROM spells
WHERE id = $1
`

func (q *Queries) DeleteSpell(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpell, id)
	return err
}

const getSpell = `-- name: GetSpell :one
SELECT id, character_id, name, level, school, casting_time, range, components, duration, description, is_prepared, created_at FROM spells
WHERE id = $1
`

func (q *Queries) GetSpell(ctx context.Context, id uuid.UUID) (Spell, error) {
	row := q.db.QueryRow(ctx, getSpell, id)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Level,
		&i.School,
		&i.CastingTime,
		&i.Range,
		&i.Components,
		&i.Duration,
		&i.Description,
		&i.IsPrepared,
		&i.CreatedAt,
	)
	return i, err
}

const listPreparedSpells = `-- name: ListPreparedSpells :many
SELECT id, character_id, name, level, school, casting_time, range, components, duration, description, is_prepared, created_at FROM spells
WHERE character_id = $1
AND is_prepared = TRUE
ORDER BY level, name
`

func (q *Queries) ListPreparedSpells(ctx context.Context, characterID uuid.UUID) ([]Spell, error) {
	rows, err := q.db.Query(ctx, listPreparedSpells, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spell{}
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Level,
			&i.School,
			&i.CastingTime,
			&i.Range,
			&i.Components,
			&i.Duration,
			&i.Description,
			&i.IsPrepared,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpells = `-- name: ListSpells :many
SELECT id, character_id, name, level, school, casting_time, range, components, duration, description, is_prepared, created_at FROM spells
WHERE character_id = $1
ORDER BY level, name
`

func (q *Queries) ListSpells(ctx context.Context, characterID uuid.UUID) ([]Spell, error) {
	rows, err := q.db.Query(ctx, listSpells, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spell{}
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Level,
			&i.School,
			&i.CastingTime,
			&i.Range,
			&i.Components,
			&i.Duration,
			&i.Description,
			&i.IsPrepared,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleSpellPrepared = `-- name: ToggleSpellPrepared :one
UPDATE spells
SET is_prepared = NOT is_prepared
WHERE id = $1
RETURNING id, character_id, name, level, school, casting_time, range, components, duration, description, is_prepared, created_at
`

func (q *Queries) ToggleSpellPrepared(ctx context.Context, id uuid.UUID) (Spell, error) {
	row := q.db.QueryRow(ctx, toggleSpellPrepared, id)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Level,
		&i.School,
		&i.CastingTime,
		&i.Range,
		&i.Components,
		&i.Duration,
		&i.Description,
		&i.IsPrepared,
		&i.CreatedAt,
	)
	return i, err
}

const updateSpell = `-- name: UpdateSpell :one
UPDATE spells
SET
    name            = $2,
    level           = $3,
    school          = $4,
    casting_time    = $5,
    range           = $6,
    components      = $7,
    duration        = $8,
    description     = $9,
    is_prepared     = $10
WHERE id = $1
RETURNING id, character_id, name, level, school, casting_time, range, components, duration, description, is_prepared, created_at
`

type UpdateSpellParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Level       int32     `json:"level"`
	School      string    `json:"school"`
	CastingTime string    `json:"casting_time"`
	Range       string    `json:"range"`
	Components  string    `json:"components"`
	Duration    string    `json:"duration"`
	Description string    `json:"description"`
	IsPrepared  bool      `json:"is_prepared"`
}

func (q *Queries) UpdateSpell(ctx context.Context, arg UpdateSpellParams) (Spell, error) {
	row := q.db.QueryRow(ctx, updateSpell,
		arg.ID,
		arg.Name,
		arg.Level,
		arg.School,
		arg.CastingTime,
		arg.Range,
		arg.Components,
		arg.Duration,
		arg.Description,
		arg.IsPrepared,
	)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.Name,
		&i.Level,
		&i.School,
		&i.CastingTime,
		&i.Range,
		&i.Components,
		&i.Duration,
		&i.Description,
		&i.IsPrepared,
		&i.CreatedAt,
	)
	return i, err
}
