// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spell_slots.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listSpellSlots = `-- name: ListSpellSlots :many
SELECT id, character_id, spell_level, total, used FROM spell_slots
WHERE character_id = $1
ORDER BY spell_level
`

func (q *Queries) ListSpellSlots(ctx context.Context, characterID uuid.UUID) ([]SpellSlot, error) {
	rows, err := q.db.Query(ctx, listSpellSlots, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpellSlot{}
	for rows.Next() {
		var i SpellSlot
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.SpellLevel,
			&i.Total,
			&i.Used,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSpellSlots = `-- name: ResetSpellSlots :exec
UPDATE spell_slots
SET used = 0
WHERE character_id = $1
`

func (q *Queries) ResetSpellSlots(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetSpellSlots, characterID)
	return err
}

const upsertSpellSlot = `-- name: UpsertSpellSlot :one
INSERT INTO spell_slots (character_id, spell_level, total, used)
VALUES ($1, $2, $3, $4)
ON CONFLICT (character_id, spell_level)
DO UPDATE SET
    total = EXCLUDED.total,
    used = EXCLUDED.used
RETURNING id, character_id, spell_level, total, used
`

type UpsertSpellSlotParams struct {
	CharacterID uuid.UUID `json:"character_id"`
	SpellLevel  int32     `json:"spell_level"`
	Total       int32     `json:"total"`
	Used        int32     `json:"used"`
}

func (q *Queries) UpsertSpellSlot(ctx context.Context, arg UpsertSpellSlotParams) (SpellSlot, error) {
	row := q.db.QueryRow(ctx, upsertSpellSlot,
		arg.CharacterID,
		arg.SpellLevel,
		arg.Total,
		arg.Used,
	)
	var i SpellSlot
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.SpellLevel,
		&i.Total,
		&i.Used,
	)
	return i, err
}

const useSpellSlot = `-- name: UseSpellSlot :one
UPDATE spell_slots
SET used = used + 1
WHERE character_id = $1
AND spell_level = $2
AND used < total
RETURNING id, character_id, spell_level, total, used
`

type UseSpellSlotParams struct {
	CharacterID uuid.UUID `json:"character_id"`
	SpellLevel  int32     `json:"spell_level"`
}

func (q *Queries) UseSpellSlot(ctx context.Context, arg UseSpellSlotParams) (SpellSlot, error) {
	row := q.db.QueryRow(ctx, useSpellSlot, arg.CharacterID, arg.SpellLevel)
	var i SpellSlot
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.SpellLevel,
		&i.Total,
		&i.Used,
	)
	return i, err
}
