// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    owner_id, is_npc,
    name, race, class, level, background, alignment, xp,
    strength, dexterity, constitution, intelligence, wisdom, charisma,
    save_prof_strength, save_prof_dexterity, save_prof_constitution,
    save_prof_intelligence, save_prof_wisdom, save_prof_charisma,
    skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics,
    skill_deception, skill_history, skill_insight, skill_intimidation,
    skill_investigation, skill_medicine, skill_nature, skill_perception,
    skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand,
    skill_stealth, skill_survival,
    max_hp, current_hp, temp_hp, armor_class, speed,
    hit_dice_type, hit_dice_remaining,
    inspiration, attunement_slots,
    training_armor, training_weapons, training_tools, training_languages,
    copper, silver, electrum, gold, platinum,
    conditions, resistances, vulnerabilities, immunities,
    personality_traits, ideals, bonds, flaws, notes,
    spellcasting_ability
) VALUES (
    $1,  $2,  $3,  $4,  $5,  $6,  $7,  $8,  $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21,
    $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35, $36, $37, $38, $39,
    $40, $41, $42, $43, $44, $45, $46,
    $47, $48,
    $49, $50, $51, $52,
    $53, $54, $55, $56, $57,
    $58, $59, $60, $61,
    $62, $63, $64, $65, $66,
    $67
)
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type CreateCharacterParams struct {
	OwnerID              uuid.UUID `json:"owner_id"`
	IsNpc                bool      `json:"is_npc"`
	Name                 string    `json:"name"`
	Race                 string    `json:"race"`
	Class                string    `json:"class"`
	Level                int32     `json:"level"`
	Background           string    `json:"background"`
	Alignment            string    `json:"alignment"`
	Xp                   int32     `json:"xp"`
	Strength             int32     `json:"strength"`
	Dexterity            int32     `json:"dexterity"`
	Constitution         int32     `json:"constitution"`
	Intelligence         int32     `json:"intelligence"`
	Wisdom               int32     `json:"wisdom"`
	Charisma             int32     `json:"charisma"`
	SaveProfStrength     bool      `json:"save_prof_strength"`
	SaveProfDexterity    bool      `json:"save_prof_dexterity"`
	SaveProfConstitution bool      `json:"save_prof_constitution"`
	SaveProfIntelligence bool      `json:"save_prof_intelligence"`
	SaveProfWisdom       bool      `json:"save_prof_wisdom"`
	SaveProfCharisma     bool      `json:"save_prof_charisma"`
	SkillAcrobatics      int32     `json:"skill_acrobatics"`
	SkillAnimalHandling  int32     `json:"skill_animal_handling"`
	SkillArcana          int32     `json:"skill_arcana"`
	SkillAthletics       int32     `json:"skill_athletics"`
	SkillDeception       int32     `json:"skill_deception"`
	SkillHistory         int32     `json:"skill_history"`
	SkillInsight         int32     `json:"skill_insight"`
	SkillIntimidation    int32     `json:"skill_intimidation"`
	SkillInvestigation   int32     `json:"skill_investigation"`
	SkillMedicine        int32     `json:"skill_medicine"`
	SkillNature          int32     `json:"skill_nature"`
	SkillPerception      int32     `json:"skill_perception"`
	SkillPerformance     int32     `json:"skill_performance"`
	SkillPersuasion      int32     `json:"skill_persuasion"`
	SkillReligion        int32     `json:"skill_religion"`
	SkillSleightOfHand   int32     `json:"skill_sleight_of_hand"`
	SkillStealth         int32     `json:"skill_stealth"`
	SkillSurvival        int32     `json:"skill_survival"`
	MaxHp                int32     `json:"max_hp"`
	CurrentHp            int32     `json:"current_hp"`
	TempHp               int32     `json:"temp_hp"`
	ArmorClass           int32     `json:"armor_class"`
	Speed                int32     `json:"speed"`
	HitDiceType          int32     `json:"hit_dice_type"`
	HitDiceRemaining     int32     `json:"hit_dice_remaining"`
	Inspiration          bool      `json:"inspiration"`
	AttunementSlots      int32     `json:"attunement_slots"`
	TrainingArmor        []string  `json:"training_armor"`
	TrainingWeapons      []string  `json:"training_weapons"`
	TrainingTools        []string  `json:"training_tools"`
	TrainingLanguages    []string  `json:"training_languages"`
	Copper               int32     `json:"copper"`
	Silver               int32     `json:"silver"`
	Electrum             int32     `json:"electrum"`
	Gold                 int32     `json:"gold"`
	Platinum             int32     `json:"platinum"`
	Conditions           []string  `json:"conditions"`
	Resistances          []string  `json:"resistances"`
	Vulnerabilities      []string  `json:"vulnerabilities"`
	Immunities           []string  `json:"immunities"`
	PersonalityTraits    string    `json:"personality_traits"`
	Ideals               string    `json:"ideals"`
	Bonds                string    `json:"bonds"`
	Flaws                string    `json:"flaws"`
	Notes                string    `json:"notes"`
	SpellcastingAbility  string    `json:"spellcasting_ability"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.OwnerID,
		arg.IsNpc,
		arg.Name,
		arg.Race,
		arg.Class,
		arg.Level,
		arg.Background,
		arg.Alignment,
		arg.Xp,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
		arg.SaveProfStrength,
		arg.SaveProfDexterity,
		arg.SaveProfConstitution,
		arg.SaveProfIntelligence,
		arg.SaveProfWisdom,
		arg.SaveProfCharisma,
		arg.SkillAcrobatics,
		arg.SkillAnimalHandling,
		arg.SkillArcana,
		arg.SkillAthletics,
		arg.SkillDeception,
		arg.SkillHistory,
		arg.SkillInsight,
		arg.SkillIntimidation,
		arg.SkillInvestigation,
		arg.SkillMedicine,
		arg.SkillNature,
		arg.SkillPerception,
		arg.SkillPerformance,
		arg.SkillPersuasion,
		arg.SkillReligion,
		arg.SkillSleightOfHand,
		arg.SkillStealth,
		arg.SkillSurvival,
		arg.MaxHp,
		arg.CurrentHp,
		arg.TempHp,
		arg.ArmorClass,
		arg.Speed,
		arg.HitDiceType,
		arg.HitDiceRemaining,
		arg.Inspiration,
		arg.AttunementSlots,
		arg.TrainingArmor,
		arg.TrainingWeapons,
		arg.TrainingTools,
		arg.TrainingLanguages,
		arg.Copper,
		arg.Silver,
		arg.Electrum,
		arg.Gold,
		arg.Platinum,
		arg.Conditions,
		arg.Resistances,
		arg.Vulnerabilities,
		arg.Immunities,
		arg.PersonalityTraits,
		arg.Ideals,
		arg.Bonds,
		arg.Flaws,
		arg.Notes,
		arg.SpellcastingAbility,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT 
    id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at,
    CEILING(1 + level / 4.0) AS proficiency_bonus,

    FLOOR((strength - 10) / 2.0) AS strength_modifier,
    FLOOR((dexterity - 10) / 2.0) AS dexterity_modifier,
    FLOOR((constitution - 10) / 2.0) AS constitution_modifier,
    FLOOR((intelligence - 10) / 2.0) AS intelligence_modifier,
    FLOOR((wisdom - 10) / 2.0) AS wisdom_modifier,
    FLOOR((charisma - 10) / 2.0) AS charisma_modifier,

    FLOOR((strength - 10) / 2.0) + save_prof_strength * CEILING(1 + level / 4.0) AS strength_saving_throw_modifier,
    FLOOR((dexterity - 10) / 2.0) + save_prof_dexterity * CEILING(1 + level / 4.0) AS dexterity_saving_throw_modifier,
    FLOOR((constitution - 10) / 2.0) + save_prof_constitution * CEILING(1 + level / 4.0) AS constitution_saving_throw_modifier,
    FLOOR((intelligence - 10) / 2.0) + save_prof_intelligence * CEILING(1 + level / 4.0) AS intelligence_saving_throw_modifier,
    FLOOR((wisdom - 10) / 2.0) + save_prof_wisdom * CEILING(1 + level / 4.0) AS wisdom_saving_throw_modifier,
    FLOOR((charisma - 10) / 2.0) + save_prof_charisma * CEILING(1 + level / 4.0) AS charisma_saving_throw_modifier,

    FLOOR((dexterity - 10) / 2.0) + skill_acrobatics * CEILING(1 + level / 4.0) AS skill_acrobatics_modifier,
    FLOOR((wisdom - 10) / 2.0) + skill_animal_handling * CEILING(1 + level / 4.0) AS skill_animal_handling_modifier,
    FLOOR((intelligence - 10) / 2.0) + skill_arcana * CEILING(1 + level / 4.0) AS skill_arcana_modifier,
    FLOOR((strength - 10) / 2.0) + skill_athletics * CEILING(1 + level / 4.0) AS skill_athletics_modifier,
    FLOOR((charisma - 10) / 2.0) + skill_deception * CEILING(1 + level / 4.0) AS skill_deception_modifier,
    FLOOR((intelligence - 10) / 2.0) + skill_history * CEILING(1 + level / 4.0) AS skill_history_modifier,
    FLOOR((wisdom - 10) / 2.0) + skill_insight * CEILING(1 + level / 4.0) AS skill_insight_modifier,
    FLOOR((charisma - 10) / 2.0) + skill_intimidation * CEILING(1 + level / 4.0) AS skill_intimidation_modifier,
    FLOOR((intelligence - 10) / 2.0) + skill_investigation * CEILING(1 + level / 4.0) AS skill_investigation_modifier,
    FLOOR((wisdom - 10) / 2.0) + skill_medicine * CEILING(1 + level / 4.0) AS skill_medicine_modifier,
    FLOOR((intelligence - 10) / 2.0) + skill_nature * CEILING(1 + level / 4.0) AS skill_nature_modifier,
    FLOOR((wisdom - 10) / 2.0) + skill_perception * CEILING(1 + level / 4.0) AS skill_perception_modifier,
    FLOOR((charisma - 10) / 2.0) + skill_performance * CEILING(1 + level / 4.0) AS skill_performance_modifier,
    FLOOR((charisma - 10) / 2.0) + skill_persuasion * CEILING(1 + level / 4.0) AS skill_persuasion_modifier,
    FLOOR((intelligence - 10) / 2.0) + skill_religion * CEILING(1 + level / 4.0) AS skill_religion_modifier,
    FLOOR((dexterity - 10) / 2.0) + skill_sleight_of_hand * CEILING(1 + level / 4.0) AS skill_sleight_of_hand_modifier,
    FLOOR((dexterity - 10) / 2.0) + skill_stealth * CEILING(1 + level / 4.0) AS skill_stealth_modifier,
    FLOOR((wisdom - 10) / 2.0) + skill_survival * CEILING(1 + level / 4.0) AS skill_survival_modifier,

    10 + FLOOR((wisdom - 10) / 2.0) + skill_perception * CEILING(1 + level / 4.0) AS passive_perception,
    10 + FLOOR((intelligence - 10) / 2.0) + skill_investigation * CEILING(1 + level / 4.0) AS passive_investigation,
    10 + FLOOR((wisdom - 10) / 2.0) + skill_insight * CEILING(1 + level / 4.0) AS passive_insight,

    FLOOR((dexterity - 10) / 2.0) AS initiative
FROM characters
WHERE id = $1
`

type GetCharacterRow struct {
	ID                              uuid.UUID          `json:"id"`
	OwnerID                         uuid.UUID          `json:"owner_id"`
	IsNpc                           bool               `json:"is_npc"`
	Name                            string             `json:"name"`
	Race                            string             `json:"race"`
	Class                           string             `json:"class"`
	Level                           int32              `json:"level"`
	Background                      string             `json:"background"`
	Alignment                       string             `json:"alignment"`
	Xp                              int32              `json:"xp"`
	Strength                        int32              `json:"strength"`
	Dexterity                       int32              `json:"dexterity"`
	Constitution                    int32              `json:"constitution"`
	Intelligence                    int32              `json:"intelligence"`
	Wisdom                          int32              `json:"wisdom"`
	Charisma                        int32              `json:"charisma"`
	SaveProfStrength                bool               `json:"save_prof_strength"`
	SaveProfDexterity               bool               `json:"save_prof_dexterity"`
	SaveProfConstitution            bool               `json:"save_prof_constitution"`
	SaveProfIntelligence            bool               `json:"save_prof_intelligence"`
	SaveProfWisdom                  bool               `json:"save_prof_wisdom"`
	SaveProfCharisma                bool               `json:"save_prof_charisma"`
	SkillAcrobatics                 int32              `json:"skill_acrobatics"`
	SkillAnimalHandling             int32              `json:"skill_animal_handling"`
	SkillArcana                     int32              `json:"skill_arcana"`
	SkillAthletics                  int32              `json:"skill_athletics"`
	SkillDeception                  int32              `json:"skill_deception"`
	SkillHistory                    int32              `json:"skill_history"`
	SkillInsight                    int32              `json:"skill_insight"`
	SkillIntimidation               int32              `json:"skill_intimidation"`
	SkillInvestigation              int32              `json:"skill_investigation"`
	SkillMedicine                   int32              `json:"skill_medicine"`
	SkillNature                     int32              `json:"skill_nature"`
	SkillPerception                 int32              `json:"skill_perception"`
	SkillPerformance                int32              `json:"skill_performance"`
	SkillPersuasion                 int32              `json:"skill_persuasion"`
	SkillReligion                   int32              `json:"skill_religion"`
	SkillSleightOfHand              int32              `json:"skill_sleight_of_hand"`
	SkillStealth                    int32              `json:"skill_stealth"`
	SkillSurvival                   int32              `json:"skill_survival"`
	MaxHp                           int32              `json:"max_hp"`
	CurrentHp                       int32              `json:"current_hp"`
	TempHp                          int32              `json:"temp_hp"`
	ArmorClass                      int32              `json:"armor_class"`
	Speed                           int32              `json:"speed"`
	HitDiceType                     int32              `json:"hit_dice_type"`
	HitDiceRemaining                int32              `json:"hit_dice_remaining"`
	DeathSaveSuccesses              int32              `json:"death_save_successes"`
	DeathSaveFailures               int32              `json:"death_save_failures"`
	SpellcastingAbility             string             `json:"spellcasting_ability"`
	Inspiration                     bool               `json:"inspiration"`
	TrainingArmor                   []string           `json:"training_armor"`
	TrainingWeapons                 []string           `json:"training_weapons"`
	TrainingTools                   []string           `json:"training_tools"`
	TrainingLanguages               []string           `json:"training_languages"`
	AttunementSlots                 int32              `json:"attunement_slots"`
	Copper                          int32              `json:"copper"`
	Silver                          int32              `json:"silver"`
	Electrum                        int32              `json:"electrum"`
	Gold                            int32              `json:"gold"`
	Platinum                        int32              `json:"platinum"`
	Conditions                      []string           `json:"conditions"`
	Resistances                     []string           `json:"resistances"`
	Vulnerabilities                 []string           `json:"vulnerabilities"`
	Immunities                      []string           `json:"immunities"`
	PersonalityTraits               string             `json:"personality_traits"`
	Ideals                          string             `json:"ideals"`
	Bonds                           string             `json:"bonds"`
	Flaws                           string             `json:"flaws"`
	Notes                           string             `json:"notes"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	ProficiencyBonus                float64            `json:"proficiency_bonus"`
	StrengthModifier                float64            `json:"strength_modifier"`
	DexterityModifier               float64            `json:"dexterity_modifier"`
	ConstitutionModifier            float64            `json:"constitution_modifier"`
	IntelligenceModifier            float64            `json:"intelligence_modifier"`
	WisdomModifier                  float64            `json:"wisdom_modifier"`
	CharismaModifier                float64            `json:"charisma_modifier"`
	StrengthSavingThrowModifier     int32              `json:"strength_saving_throw_modifier"`
	DexteritySavingThrowModifier    int32              `json:"dexterity_saving_throw_modifier"`
	ConstitutionSavingThrowModifier int32              `json:"constitution_saving_throw_modifier"`
	IntelligenceSavingThrowModifier int32              `json:"intelligence_saving_throw_modifier"`
	WisdomSavingThrowModifier       int32              `json:"wisdom_saving_throw_modifier"`
	CharismaSavingThrowModifier     int32              `json:"charisma_saving_throw_modifier"`
	SkillAcrobaticsModifier         int32              `json:"skill_acrobatics_modifier"`
	SkillAnimalHandlingModifier     int32              `json:"skill_animal_handling_modifier"`
	SkillArcanaModifier             int32              `json:"skill_arcana_modifier"`
	SkillAthleticsModifier          int32              `json:"skill_athletics_modifier"`
	SkillDeceptionModifier          int32              `json:"skill_deception_modifier"`
	SkillHistoryModifier            int32              `json:"skill_history_modifier"`
	SkillInsightModifier            int32              `json:"skill_insight_modifier"`
	SkillIntimidationModifier       int32              `json:"skill_intimidation_modifier"`
	SkillInvestigationModifier      int32              `json:"skill_investigation_modifier"`
	SkillMedicineModifier           int32              `json:"skill_medicine_modifier"`
	SkillNatureModifier             int32              `json:"skill_nature_modifier"`
	SkillPerceptionModifier         int32              `json:"skill_perception_modifier"`
	SkillPerformanceModifier        int32              `json:"skill_performance_modifier"`
	SkillPersuasionModifier         int32              `json:"skill_persuasion_modifier"`
	SkillReligionModifier           int32              `json:"skill_religion_modifier"`
	SkillSleightOfHandModifier      int32              `json:"skill_sleight_of_hand_modifier"`
	SkillStealthModifier            int32              `json:"skill_stealth_modifier"`
	SkillSurvivalModifier           int32              `json:"skill_survival_modifier"`
	PassivePerception               int32              `json:"passive_perception"`
	PassiveInvestigation            int32              `json:"passive_investigation"`
	PassiveInsight                  int32              `json:"passive_insight"`
	Initiative                      float64            `json:"initiative"`
}

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (GetCharacterRow, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i GetCharacterRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProficiencyBonus,
		&i.StrengthModifier,
		&i.DexterityModifier,
		&i.ConstitutionModifier,
		&i.IntelligenceModifier,
		&i.WisdomModifier,
		&i.CharismaModifier,
		&i.StrengthSavingThrowModifier,
		&i.DexteritySavingThrowModifier,
		&i.ConstitutionSavingThrowModifier,
		&i.IntelligenceSavingThrowModifier,
		&i.WisdomSavingThrowModifier,
		&i.CharismaSavingThrowModifier,
		&i.SkillAcrobaticsModifier,
		&i.SkillAnimalHandlingModifier,
		&i.SkillArcanaModifier,
		&i.SkillAthleticsModifier,
		&i.SkillDeceptionModifier,
		&i.SkillHistoryModifier,
		&i.SkillInsightModifier,
		&i.SkillIntimidationModifier,
		&i.SkillInvestigationModifier,
		&i.SkillMedicineModifier,
		&i.SkillNatureModifier,
		&i.SkillPerceptionModifier,
		&i.SkillPerformanceModifier,
		&i.SkillPersuasionModifier,
		&i.SkillReligionModifier,
		&i.SkillSleightOfHandModifier,
		&i.SkillStealthModifier,
		&i.SkillSurvivalModifier,
		&i.PassivePerception,
		&i.PassiveInvestigation,
		&i.PassiveInsight,
		&i.Initiative,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
ORDER BY name
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.SpellcastingAbility,
			&i.Inspiration,
			&i.TrainingArmor,
			&i.TrainingWeapons,
			&i.TrainingTools,
			&i.TrainingLanguages,
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			&i.Conditions,
			&i.Resistances,
			&i.Vulnerabilities,
			&i.Immunities,
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNPCs = `-- name: ListNPCs :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE is_npc = TRUE
ORDER BY name
`

func (q *Queries) ListNPCs(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, listNPCs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.SpellcastingAbility,
			&i.Inspiration,
			&i.TrainingArmor,
			&i.TrainingWeapons,
			&i.TrainingTools,
			&i.TrainingLanguages,
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			&i.Conditions,
			&i.Resistances,
			&i.Vulnerabilities,
			&i.Immunities,
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerCharacters = `-- name: ListPlayerCharacters :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE is_npc = FALSE
ORDER BY name
`

func (q *Queries) ListPlayerCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, listPlayerCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.SpellcastingAbility,
			&i.Inspiration,
			&i.TrainingArmor,
			&i.TrainingWeapons,
			&i.TrainingTools,
			&i.TrainingLanguages,
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			&i.Conditions,
			&i.Resistances,
			&i.Vulnerabilities,
			&i.Immunities,
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCharacters = `-- name: ListUserCharacters :many
SELECT id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at FROM characters
WHERE owner_id = $1
ORDER BY name
`

func (q *Queries) ListUserCharacters(ctx context.Context, ownerID uuid.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listUserCharacters, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsNpc,
			&i.Name,
			&i.Race,
			&i.Class,
			&i.Level,
			&i.Background,
			&i.Alignment,
			&i.Xp,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.SaveProfStrength,
			&i.SaveProfDexterity,
			&i.SaveProfConstitution,
			&i.SaveProfIntelligence,
			&i.SaveProfWisdom,
			&i.SaveProfCharisma,
			&i.SkillAcrobatics,
			&i.SkillAnimalHandling,
			&i.SkillArcana,
			&i.SkillAthletics,
			&i.SkillDeception,
			&i.SkillHistory,
			&i.SkillInsight,
			&i.SkillIntimidation,
			&i.SkillInvestigation,
			&i.SkillMedicine,
			&i.SkillNature,
			&i.SkillPerception,
			&i.SkillPerformance,
			&i.SkillPersuasion,
			&i.SkillReligion,
			&i.SkillSleightOfHand,
			&i.SkillStealth,
			&i.SkillSurvival,
			&i.MaxHp,
			&i.CurrentHp,
			&i.TempHp,
			&i.ArmorClass,
			&i.Speed,
			&i.HitDiceType,
			&i.HitDiceRemaining,
			&i.DeathSaveSuccesses,
			&i.DeathSaveFailures,
			&i.SpellcastingAbility,
			&i.Inspiration,
			&i.TrainingArmor,
			&i.TrainingWeapons,
			&i.TrainingTools,
			&i.TrainingLanguages,
			&i.AttunementSlots,
			&i.Copper,
			&i.Silver,
			&i.Electrum,
			&i.Gold,
			&i.Platinum,
			&i.Conditions,
			&i.Resistances,
			&i.Vulnerabilities,
			&i.Immunities,
			&i.PersonalityTraits,
			&i.Ideals,
			&i.Bonds,
			&i.Flaws,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const longRest = `-- name: LongRest :one
UPDATE characters
SET
    current_hp              = max_hp,
    temp_hp                 = 0,
    hit_dice_remaining      = GREATEST(hit_dice_remaining + (level / 2), level),
    death_save_successes    = 0,
    death_save_failures     = 0,
    conditions              = '{}',
    updated_at              = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

func (q *Queries) LongRest(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, longRest, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetDeathSaves = `-- name: ResetDeathSaves :one
UPDATE characters
SET
    death_save_successes    = 0,
    death_save_failures     = 0,
    updated_at              = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

func (q *Queries) ResetDeathSaves(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, resetDeathSaves, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const shortRest = `-- name: ShortRest :one
UPDATE characters
SET
    hit_dice_remaining      = GREATEST(hit_dice_remaining - $2, 0),
    current_hp              = LEAST(current_hp + $3, max_hp),
    temp_hp                 = 0,
    updated_at              = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type ShortRestParams struct {
	ID               uuid.UUID `json:"id"`
	HitDiceRemaining int32     `json:"hit_dice_remaining"`
	CurrentHp        int32     `json:"current_hp"`
}

func (q *Queries) ShortRest(ctx context.Context, arg ShortRestParams) (Character, error) {
	row := q.db.QueryRow(ctx, shortRest, arg.ID, arg.HitDiceRemaining, arg.CurrentHp)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterAbilityScores = `-- name: UpdateCharacterAbilityScores :one
UPDATE characters
SET
    strength               = COALESCE($1, strength),
    dexterity              = COALESCE($2, dexterity),
    constitution           = COALESCE($3, constitution),
    intelligence           = COALESCE($4, intelligence),
    wisdom                 = COALESCE($5, wisdom),
    charisma               = COALESCE($6, charisma),
    save_prof_strength     = COALESCE($7, save_prof_strength),
    save_prof_dexterity    = COALESCE($8, save_prof_dexterity),
    save_prof_constitution = COALESCE($9, save_prof_constitution),
    save_prof_intelligence = COALESCE($10, save_prof_intelligence),
    save_prof_wisdom       = COALESCE($11, save_prof_wisdom),
    save_prof_charisma     = COALESCE($12, save_prof_charisma),
    updated_at             = NOW()
WHERE id = $13
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterAbilityScoresParams struct {
	Strength             *int32    `json:"strength"`
	Dexterity            *int32    `json:"dexterity"`
	Constitution         *int32    `json:"constitution"`
	Intelligence         *int32    `json:"intelligence"`
	Wisdom               *int32    `json:"wisdom"`
	Charisma             *int32    `json:"charisma"`
	SaveProfStrength     *bool     `json:"save_prof_strength"`
	SaveProfDexterity    *bool     `json:"save_prof_dexterity"`
	SaveProfConstitution *bool     `json:"save_prof_constitution"`
	SaveProfIntelligence *bool     `json:"save_prof_intelligence"`
	SaveProfWisdom       *bool     `json:"save_prof_wisdom"`
	SaveProfCharisma     *bool     `json:"save_prof_charisma"`
	ID                   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCharacterAbilityScores(ctx context.Context, arg UpdateCharacterAbilityScoresParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterAbilityScores,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
		arg.SaveProfStrength,
		arg.SaveProfDexterity,
		arg.SaveProfConstitution,
		arg.SaveProfIntelligence,
		arg.SaveProfWisdom,
		arg.SaveProfCharisma,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterCurrency = `-- name: UpdateCharacterCurrency :one
UPDATE characters
SET
    copper                 = COALESCE($1, copper),
    silver                 = COALESCE($2, silver),
    electrum               = COALESCE($3, electrum),
    gold                   = COALESCE($4, gold),
    platinum               = COALESCE($5, platinum),
    conditions             = COALESCE($6, conditions),
    updated_at             = NOW()
WHERE id = $7
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterCurrencyParams struct {
	Copper     *int32    `json:"copper"`
	Silver     *int32    `json:"silver"`
	Electrum   *int32    `json:"electrum"`
	Gold       *int32    `json:"gold"`
	Platinum   *int32    `json:"platinum"`
	Conditions []string  `json:"conditions"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCharacterCurrency(ctx context.Context, arg UpdateCharacterCurrencyParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterCurrency,
		arg.Copper,
		arg.Silver,
		arg.Electrum,
		arg.Gold,
		arg.Platinum,
		arg.Conditions,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterHP = `-- name: UpdateCharacterHP :one
UPDATE characters
SET
    current_hp = $2,
    temp_hp    = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterHPParams struct {
	ID        uuid.UUID `json:"id"`
	CurrentHp int32     `json:"current_hp"`
	TempHp    int32     `json:"temp_hp"`
}

func (q *Queries) UpdateCharacterHP(ctx context.Context, arg UpdateCharacterHPParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterHP, arg.ID, arg.CurrentHp, arg.TempHp)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterInfo = `-- name: UpdateCharacterInfo :one
UPDATE characters
SET
    name                   = COALESCE($1, name),
    race                   = COALESCE($2, race),
    background             = COALESCE($3, background),
    alignment              = COALESCE($4, alignment),
    inspiration            = COALESCE($5, inspiration),
    speed                  = COALESCE($6, speed),
    ideals                 = COALESCE($7, ideals),
    bonds                  = COALESCE($8, bonds),
    flaws                  = COALESCE($9, flaws),
    notes                  = COALESCE($10, notes),
    updated_at             = NOW()
WHERE id = $11
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterInfoParams struct {
	Name        *string   `json:"name"`
	Race        *string   `json:"race"`
	Background  *string   `json:"background"`
	Alignment   *string   `json:"alignment"`
	Inspiration *bool     `json:"inspiration"`
	Speed       *int32    `json:"speed"`
	Ideals      *string   `json:"ideals"`
	Bonds       *string   `json:"bonds"`
	Flaws       *string   `json:"flaws"`
	Notes       *string   `json:"notes"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCharacterInfo(ctx context.Context, arg UpdateCharacterInfoParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterInfo,
		arg.Name,
		arg.Race,
		arg.Background,
		arg.Alignment,
		arg.Inspiration,
		arg.Speed,
		arg.Ideals,
		arg.Bonds,
		arg.Flaws,
		arg.Notes,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterLevel = `-- name: UpdateCharacterLevel :one
UPDATE characters
SET
    class                  = COALESCE($1, class),
    level                  = COALESCE($2, level),
    xp                     = COALESCE($3, xp),
    max_hp                 = COALESCE($4, max_hp),
    hit_dice_type          = COALESCE($5, hit_dice_type),
    hit_dice_remaining     = COALESCE($6, hit_dice_remaining),
    updated_at             = NOW()
WHERE id = $7
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterLevelParams struct {
	Class            *string   `json:"class"`
	Level            *int32    `json:"level"`
	Xp               *int32    `json:"xp"`
	MaxHp            *int32    `json:"max_hp"`
	HitDiceType      *int32    `json:"hit_dice_type"`
	HitDiceRemaining *int32    `json:"hit_dice_remaining"`
	ID               uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCharacterLevel(ctx context.Context, arg UpdateCharacterLevelParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterLevel,
		arg.Class,
		arg.Level,
		arg.Xp,
		arg.MaxHp,
		arg.HitDiceType,
		arg.HitDiceRemaining,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterSkills = `-- name: UpdateCharacterSkills :one
UPDATE characters
SET
    skill_acrobatics       = COALESCE($1, skill_acrobatics),
    skill_animal_handling  = COALESCE($2, skill_animal_handling),
    skill_arcana           = COALESCE($3, skill_arcana),
    skill_athletics        = COALESCE($4, skill_athletics),
    skill_deception        = COALESCE($5, skill_deception),
    skill_history          = COALESCE($6, skill_history),
    skill_insight          = COALESCE($7, skill_insight),
    skill_intimidation     = COALESCE($8, skill_intimidation),
    skill_investigation    = COALESCE($9, skill_investigation),
    skill_medicine         = COALESCE($10, skill_medicine),
    skill_nature           = COALESCE($11, skill_nature),
    skill_perception       = COALESCE($12, skill_perception),
    skill_performance      = COALESCE($13, skill_performance),
    skill_persuasion       = COALESCE($14, skill_persuasion),
    skill_religion         = COALESCE($15, skill_religion),
    skill_sleight_of_hand  = COALESCE($16, skill_sleight_of_hand),
    skill_stealth          = COALESCE($17, skill_stealth),
    skill_survival         = COALESCE($18, skill_survival),
    updated_at             = NOW()
WHERE id = $19
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterSkillsParams struct {
	SkillAcrobatics     *int32    `json:"skill_acrobatics"`
	SkillAnimalHandling *int32    `json:"skill_animal_handling"`
	SkillArcana         *int32    `json:"skill_arcana"`
	SkillAthletics      *int32    `json:"skill_athletics"`
	SkillDeception      *int32    `json:"skill_deception"`
	SkillHistory        *int32    `json:"skill_history"`
	SkillInsight        *int32    `json:"skill_insight"`
	SkillIntimidation   *int32    `json:"skill_intimidation"`
	SkillInvestigation  *int32    `json:"skill_investigation"`
	SkillMedicine       *int32    `json:"skill_medicine"`
	SkillNature         *int32    `json:"skill_nature"`
	SkillPerception     *int32    `json:"skill_perception"`
	SkillPerformance    *int32    `json:"skill_performance"`
	SkillPersuasion     *int32    `json:"skill_persuasion"`
	SkillReligion       *int32    `json:"skill_religion"`
	SkillSleightOfHand  *int32    `json:"skill_sleight_of_hand"`
	SkillStealth        *int32    `json:"skill_stealth"`
	SkillSurvival       *int32    `json:"skill_survival"`
	ID                  uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCharacterSkills(ctx context.Context, arg UpdateCharacterSkillsParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterSkills,
		arg.SkillAcrobatics,
		arg.SkillAnimalHandling,
		arg.SkillArcana,
		arg.SkillAthletics,
		arg.SkillDeception,
		arg.SkillHistory,
		arg.SkillInsight,
		arg.SkillIntimidation,
		arg.SkillInvestigation,
		arg.SkillMedicine,
		arg.SkillNature,
		arg.SkillPerception,
		arg.SkillPerformance,
		arg.SkillPersuasion,
		arg.SkillReligion,
		arg.SkillSleightOfHand,
		arg.SkillStealth,
		arg.SkillSurvival,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterTraining = `-- name: UpdateCharacterTraining :one
UPDATE characters
SET
    armor_class            = COALESCE($1, armor_class),
    attunement_slots       = COALESCE($2, attunement_slots),
    training_armor         = COALESCE($3, training_armor),
    training_weapons       = COALESCE($4, training_weapons),
    training_tools         = COALESCE($5, training_tools),
    training_languages     = COALESCE($6, training_languages),
    spellcasting_ability   = COALESCE($7, spellcasting_ability),
    resistances            = COALESCE($8, resistances),
    vulnerabilities        = COALESCE($9, vulnerabilities),
    immunities             = COALESCE($10, immunities),
    updated_at             = NOW()
WHERE id = $11
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateCharacterTrainingParams struct {
	ArmorClass          *int32    `json:"armor_class"`
	AttunementSlots     *int32    `json:"attunement_slots"`
	TrainingArmor       []string  `json:"training_armor"`
	TrainingWeapons     []string  `json:"training_weapons"`
	TrainingTools       []string  `json:"training_tools"`
	TrainingLanguages   []string  `json:"training_languages"`
	SpellcastingAbility *string   `json:"spellcasting_ability"`
	Resistances         []string  `json:"resistances"`
	Vulnerabilities     []string  `json:"vulnerabilities"`
	Immunities          []string  `json:"immunities"`
	ID                  uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCharacterTraining(ctx context.Context, arg UpdateCharacterTrainingParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterTraining,
		arg.ArmorClass,
		arg.AttunementSlots,
		arg.TrainingArmor,
		arg.TrainingWeapons,
		arg.TrainingTools,
		arg.TrainingLanguages,
		arg.SpellcastingAbility,
		arg.Resistances,
		arg.Vulnerabilities,
		arg.Immunities,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConditions = `-- name: UpdateConditions :one
UPDATE characters
SET
    conditions = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateConditionsParams struct {
	ID         uuid.UUID `json:"id"`
	Conditions []string  `json:"conditions"`
}

func (q *Queries) UpdateConditions(ctx context.Context, arg UpdateConditionsParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateConditions, arg.ID, arg.Conditions)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeathSaves = `-- name: UpdateDeathSaves :one
UPDATE characters
SET
    death_save_successes    = $2,
    death_save_failures     = $3,
    updated_at              = NOW()
WHERE id = $1
RETURNING id, owner_id, is_npc, name, race, class, level, background, alignment, xp, strength, dexterity, constitution, intelligence, wisdom, charisma, save_prof_strength, save_prof_dexterity, save_prof_constitution, save_prof_intelligence, save_prof_wisdom, save_prof_charisma, skill_acrobatics, skill_animal_handling, skill_arcana, skill_athletics, skill_deception, skill_history, skill_insight, skill_intimidation, skill_investigation, skill_medicine, skill_nature, skill_perception, skill_performance, skill_persuasion, skill_religion, skill_sleight_of_hand, skill_stealth, skill_survival, max_hp, current_hp, temp_hp, armor_class, speed, hit_dice_type, hit_dice_remaining, death_save_successes, death_save_failures, spellcasting_ability, inspiration, training_armor, training_weapons, training_tools, training_languages, attunement_slots, copper, silver, electrum, gold, platinum, conditions, resistances, vulnerabilities, immunities, personality_traits, ideals, bonds, flaws, notes, created_at, updated_at
`

type UpdateDeathSavesParams struct {
	ID                 uuid.UUID `json:"id"`
	DeathSaveSuccesses int32     `json:"death_save_successes"`
	DeathSaveFailures  int32     `json:"death_save_failures"`
}

func (q *Queries) UpdateDeathSaves(ctx context.Context, arg UpdateDeathSavesParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateDeathSaves, arg.ID, arg.DeathSaveSuccesses, arg.DeathSaveFailures)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsNpc,
		&i.Name,
		&i.Race,
		&i.Class,
		&i.Level,
		&i.Background,
		&i.Alignment,
		&i.Xp,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.SaveProfStrength,
		&i.SaveProfDexterity,
		&i.SaveProfConstitution,
		&i.SaveProfIntelligence,
		&i.SaveProfWisdom,
		&i.SaveProfCharisma,
		&i.SkillAcrobatics,
		&i.SkillAnimalHandling,
		&i.SkillArcana,
		&i.SkillAthletics,
		&i.SkillDeception,
		&i.SkillHistory,
		&i.SkillInsight,
		&i.SkillIntimidation,
		&i.SkillInvestigation,
		&i.SkillMedicine,
		&i.SkillNature,
		&i.SkillPerception,
		&i.SkillPerformance,
		&i.SkillPersuasion,
		&i.SkillReligion,
		&i.SkillSleightOfHand,
		&i.SkillStealth,
		&i.SkillSurvival,
		&i.MaxHp,
		&i.CurrentHp,
		&i.TempHp,
		&i.ArmorClass,
		&i.Speed,
		&i.HitDiceType,
		&i.HitDiceRemaining,
		&i.DeathSaveSuccesses,
		&i.DeathSaveFailures,
		&i.SpellcastingAbility,
		&i.Inspiration,
		&i.TrainingArmor,
		&i.TrainingWeapons,
		&i.TrainingTools,
		&i.TrainingLanguages,
		&i.AttunementSlots,
		&i.Copper,
		&i.Silver,
		&i.Electrum,
		&i.Gold,
		&i.Platinum,
		&i.Conditions,
		&i.Resistances,
		&i.Vulnerabilities,
		&i.Immunities,
		&i.PersonalityTraits,
		&i.Ideals,
		&i.Bonds,
		&i.Flaws,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
