// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) (CombatParticipant, error)
	CountAttunedItems(ctx context.Context, characterID uuid.UUID) (int64, error)
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	CreateEncounter(ctx context.Context, name string) (CombatEncounter, error)
	CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error)
	CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error)
	CreateSpell(ctx context.Context, arg CreateSpellParams) (Spell, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeactivateParticipant(ctx context.Context, id uuid.UUID) (CombatParticipant, error)
	DeleteCharacter(ctx context.Context, id uuid.UUID) error
	DeleteEncounter(ctx context.Context, id uuid.UUID) error
	DeleteFeature(ctx context.Context, id uuid.UUID) error
	DeleteInventoryItem(ctx context.Context, id uuid.UUID) error
	DeleteSpell(ctx context.Context, id uuid.UUID) error
	EndEncounter(ctx context.Context, id uuid.UUID) (CombatEncounter, error)
	GetActiveEncounter(ctx context.Context) (CombatEncounter, error)
	GetCharacter(ctx context.Context, id uuid.UUID) (GetCharacterRow, error)
	GetEncounter(ctx context.Context, id uuid.UUID) (CombatEncounter, error)
	GetInventoryItem(ctx context.Context, id uuid.UUID) (InventoryItem, error)
	GetParticipant(ctx context.Context, id uuid.UUID) (CombatParticipant, error)
	GetSpell(ctx context.Context, id uuid.UUID) (Spell, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListActiveParticipants(ctx context.Context, encounterID uuid.UUID) ([]CombatParticipant, error)
	ListCharacters(ctx context.Context) ([]Character, error)
	ListEncounters(ctx context.Context) ([]CombatEncounter, error)
	ListFeatures(ctx context.Context, characterID uuid.UUID) ([]Feature, error)
	ListFeaturesByActionType(ctx context.Context, arg ListFeaturesByActionTypeParams) ([]Feature, error)
	ListInventoryItems(ctx context.Context, characterID uuid.UUID) ([]InventoryItem, error)
	ListNPCs(ctx context.Context) ([]Character, error)
	ListParticipants(ctx context.Context, encounterID uuid.UUID) ([]CombatParticipant, error)
	ListPlayerCharacters(ctx context.Context) ([]Character, error)
	ListPreparedSpells(ctx context.Context, characterID uuid.UUID) ([]Spell, error)
	ListSpellSlots(ctx context.Context, characterID uuid.UUID) ([]SpellSlot, error)
	ListSpells(ctx context.Context, characterID uuid.UUID) ([]Spell, error)
	ListUserCharacters(ctx context.Context, ownerID uuid.UUID) ([]Character, error)
	LongRest(ctx context.Context, id uuid.UUID) (Character, error)
	NextRound(ctx context.Context, id uuid.UUID) (CombatEncounter, error)
	RemoveParticipant(ctx context.Context, id uuid.UUID) error
	ResetDeathSaves(ctx context.Context, id uuid.UUID) (Character, error)
	ResetSpellSlots(ctx context.Context, characterID uuid.UUID) error
	ShortRest(ctx context.Context, arg ShortRestParams) (Character, error)
	StartEncounter(ctx context.Context, id uuid.UUID) (CombatEncounter, error)
	ToggleParticipantConcentration(ctx context.Context, id uuid.UUID) (CombatParticipant, error)
	ToggleSpellPrepared(ctx context.Context, id uuid.UUID) (Spell, error)
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error)
	UpdateCharacterHP(ctx context.Context, arg UpdateCharacterHPParams) (Character, error)
	UpdateConditions(ctx context.Context, arg UpdateConditionsParams) (Character, error)
	UpdateDeathSaves(ctx context.Context, arg UpdateDeathSavesParams) (Character, error)
	UpdateFeature(ctx context.Context, arg UpdateFeatureParams) (Feature, error)
	UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error)
	UpdateParticipantConditions(ctx context.Context, arg UpdateParticipantConditionsParams) (CombatParticipant, error)
	UpdateParticipantHP(ctx context.Context, arg UpdateParticipantHPParams) (CombatParticipant, error)
	UpdateParticipantInitiative(ctx context.Context, arg UpdateParticipantInitiativeParams) (CombatParticipant, error)
	UpdateParticipantTempHP(ctx context.Context, arg UpdateParticipantTempHPParams) (CombatParticipant, error)
	UpdateSpell(ctx context.Context, arg UpdateSpellParams) (Spell, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error)
	UpsertSpellSlot(ctx context.Context, arg UpsertSpellSlotParams) (SpellSlot, error)
	UseSpellSlot(ctx context.Context, arg UseSpellSlotParams) (SpellSlot, error)
}

var _ Querier = (*Queries)(nil)
